### Add data users
POST http://localhost:3000/user
Content-Type: application/json

{
  "nama_user": "admin",
  "email": "admin11@mail.com",
  "username": "admin12377",
  "password": "12345678"
}

### GET request data users
GET http://localhost:3000/user

### Delete data users
DELETE http://localhost:3000/user/4